[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
halflife_passport = "HLFpass1111111111111111111111111111111111111"
halflife_consumer = "HLFcons1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
