// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HalflifeDestinationRegistry as Registry} from "../src/HalflifeDestinationRegistry.sol";
import {IInterchainSecurityModule as IIsm} from "../src/IInterchainSecurityModule.sol";

/// @notice Cross-implementation conformance: decode bytes produced by the Rust
///         encoder, not by this test.
///
/// @dev The other test file builds cores in Solidity and decodes them in
///      Solidity, which proves only that this contract agrees with itself. The
///      vectors below come from `fixtures/vectors.json`, generated by
///      `halflife-core` and already verified byte-for-byte by an independent
///      Node implementation.
///
///      This is the same discipline that caught the 64-bit JSON defect before
///      the format froze: a decoder checked only against its own encoder will
///      happily agree with a mistake.
///
///      Regenerate with: `halflife vectors generate`
contract ConformanceTest is Test {
    Registry internal registry;

    address internal constant MAILBOX = address(0xBEEF);
    uint32 internal constant ORIGIN = 1399811149;
    bytes32 internal constant SENDER = bytes32(uint256(0xA11CE));

    /// The vectors' circuit_hash and issuer, taken from `fixtures/vectors.json`.
    /// The issuer is the ed25519 public key for the published test seed.
    bytes32 internal constant VEC_CIRCUIT =
        0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes32 internal constant VEC_ISSUER =
        0xd75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a;

    /// A non-null ISM, because the registry refuses to exist without one.
    function _aggIsm() internal returns (IIsm) {
        return IIsm(address(new TestAggIsm()));
    }

    function setUp() public {
        registry = new Registry(MAILBOX, ORIGIN, SENDER, _aggIsm());
    }

    function _deliver(bytes memory core) internal {
        vm.prank(MAILBOX);
        registry.handle(ORIGIN, SENDER, core);
    }

    /// vector: valid_c1_seq1
    function test_vector_valid_c1_seq1() public {
        _deliver(
            hex"011111111111111111111111111111111111111111111111111111111111111111d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a0100000000000000010100f1536500000000804255650000000022222222222222222222222222222222222222222222222222222222222222220000"
        );
        Registry.Passport memory p = registry.get(VEC_CIRCUIT, VEC_ISSUER);
        assertEq(p.sequence, 1, "sequence");
        assertEq(p.capability, 1, "capability");
        assertEq(p.status, 1, "status VALID");
        assertEq(p.issuedAt, 1_700_000_000, "issuedAt");
        assertEq(p.expiresAt, 1_700_086_400, "expiresAt");
        assertEq(p.advisoryCount, 0, "advisoryCount");
    }

    /// vector: invalid_three_advisories
    function test_vector_invalid_three_advisories() public {
        _deliver(
            hex"011111111111111111111111111111111111111111111111111111111111111111d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a0200000000000000010200f1536500000000804255650000000022222222222222222222222222222222222222222222222222222222222222220300"
        );
        Registry.Passport memory p = registry.get(VEC_CIRCUIT, VEC_ISSUER);
        assertEq(p.sequence, 2);
        assertEq(p.status, 2, "status INVALID");
        assertEq(p.advisoryCount, 3, "advisoryCount");
    }

    /// vector: valid_c5_seq7
    function test_vector_valid_c5_seq7() public {
        _deliver(
            hex"011111111111111111111111111111111111111111111111111111111111111111d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a0700000000000000050100f1536500000000804255650000000022222222222222222222222222222222222222222222222222222222222222220000"
        );
        Registry.Passport memory p = registry.get(VEC_CIRCUIT, VEC_ISSUER);
        assertEq(p.sequence, 7);
        assertEq(p.capability, 5, "capability C5");
    }

    /// vector: boundary_extremes
    ///
    /// The one that matters. u64::MAX, i64::MIN, i64::MAX, u16::MAX — every
    /// width at its edge, where a byte-order or sign mistake shows up and
    /// nowhere else. This is the vector that failed in the Node implementation
    /// and exposed the JSON float64 defect.
    function test_vector_boundary_extremes() public {
        _deliver(
            hex"011111111111111111111111111111111111111111111111111111111111111111d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511affffffffffffffff00010000000000000080ffffffffffffff7f2222222222222222222222222222222222222222222222222222222222222222ffff"
        );
        Registry.Passport memory p = registry.get(VEC_CIRCUIT, VEC_ISSUER);
        assertEq(p.sequence, type(uint64).max, "sequence u64::MAX");
        assertEq(p.capability, 0, "capability C0");
        assertEq(p.issuedAt, type(int64).min, "issuedAt i64::MIN");
        assertEq(p.expiresAt, type(int64).max, "expiresAt i64::MAX");
        assertEq(p.advisoryCount, type(uint16).max, "advisoryCount u16::MAX");
    }

    /// A passport with i64::MIN issuance and i64::MAX expiry must still read as
    /// Valid rather than wrapping into Stale.
    function test_extremeExpiryDoesNotWrap() public {
        _deliver(
            hex"011111111111111111111111111111111111111111111111111111111111111111d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511affffffffffffffff00010000000000000080ffffffffffffff7f2222222222222222222222222222222222222222222222222222222222222222ffff"
        );
        vm.warp(1_700_000_000);
        assertEq(
            uint256(registry.statusNow(VEC_CIRCUIT, VEC_ISSUER)),
            uint256(Registry.Effective.Valid)
        );
    }
}

/// Minimal AGGREGATION-type module for tests.
contract TestAggIsm is IIsm {
    function moduleType() external pure returns (uint8) {
        return uint8(IIsm.Types.AGGREGATION);
    }

    function verify(bytes calldata, bytes calldata) external pure returns (bool) {
        return true;
    }
}
